name: GitHub Actions Workflow
on:
  push:
    branches:
      - master  # Trigger on changes to the master branch
      - main    # Trigger on changes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Use the node version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build  # Generate the build directory

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages  # The branch the action should deploy to
        folder: build     # The folder the action should deploy
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow